# Generated by Django 6.0.1 on 2026-02-04 13:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='current_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DRAFT', '임시저장'), ('OPEN', '모집중'), ('CLOSED', '모집완료'), ('EXECUTED', '대출시작'), ('SETTLED', '정산완료')], db_index=True, default='DRAFT', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='target_amount',
            field=models.DecimalField(decimal_places=0, default=100000000, max_digits=15),
        ),
        migrations.CreateModel(
            name='ProductStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('DRAFT', '임시저장'), ('OPEN', '모집중'), ('CLOSED', '모집완료'), ('EXECUTED', '대출시작'), ('SETTLED', '정산완료')], max_length=10)),
                ('to_status', models.CharField(choices=[('DRAFT', '임시저장'), ('OPEN', '모집중'), ('CLOSED', '모집완료'), ('EXECUTED', '대출시작'), ('SETTLED', '정산완료')], max_length=10)),
                ('changed_by', models.CharField(max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
