# Generated by Django 6.0.1 on 2026-02-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_created_at_product_current_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstatushistory',
            name='changed_by',
            field=models.CharField(default='system', max_length=100),
        ),
    ]
