# Generated by Django 6.0.1 on 2026-02-11 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productstatushistory_changed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstatushistory',
            name='changed_by',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('investor_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='products.product')),
            ],
        ),
    ]
